config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  resource :user, only: %i[show edit update]
  resources :users, only: :index

  namespace :users do
    resources :lodgings do
      resources :roommates, only: :create
      resources :rooms, only: %i[index create destroy]
      resource :calendars, only: %i[show create destroy update] do
        get 'my_calendar', on: :member
      end
    end
  end

  get '/edit-profile', to: 'accounts#edit', as: 'edit_profile'
  patch '/edit-profile', to: 'accounts#update'
  delete '/account_season_pass/:season_pass_id', to: 'accounts#season_pass_destroy', as: 'remove_season_pass'

  devise_for :accounts, controllers: {
    omniauth_callbacks: 'accounts/omniauth_callbacks',
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations'
  }
end

app/models/lodging.rb
# frozen_string_literal: true

class Lodging < ApplicationRecord
  has_many :roommates, dependent: :destroy
  has_many :users, through: :roommates
  has_many :rooms
  has_many :calendars, dependent: :destroy

  #   validates :max_capacity, numericality: { greater_than: 0, less_than: 101 }, if: { status: :published}

  enum status: {
    draft: 'draft',
    published: 'published',
    archived: 'archived'
  }, _default: 'draft'

  def full_address
    st = street
    st = street + " #{address2}" if address2
    st + " #{city}, #{state} #{zip_code}"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :roommates
  has_many :lodgings, through: :roommates
  belongs_to :account
  has_many :calendars, dependent: :destroy

  validates :first_name, :last_name, :ride_type, presence: true, length: { minimum: 2 }

  enum :ride_type, {
    ski: 'ski',
    snowboard: 'snowboard',
    both: 'ski and snowboard'
  }, prefix: true, _default: 'ski'

  enum :level, {
    beginner: 'beginner',
    intermediate: 'intermediate',
    advanced: 'advanced'
  }, _default: 'beginner'

  def initials
    "#{first_name&.first || ''}#{last_name&.first || ''}".upcase
  end
end

app/controllers/users/calendars_controller.rb
# frozen_string_literal: true

module Users
  class CalendarsController < ApplicationController
    before_action :authenticate_account!

    def show
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @lodging_calendars = @lodging.calendars.grouped_by_date_with_avatars(params[:start_date]&.to_date || Date.today)
    end

    def my_calendar
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @calendars = current_account.user.calendars.where(lodging_id: params[:lodging_id])
    end

    def create
      @calendar = current_account.user.calendars.new(create_calendar_params.except(:start_date))

      if @calendar.save
        redirect_to my_calendar_users_lodging_calendars_path(start_date: create_calendar_params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    def update
      @calendar = current_account.user.calendars.find(params[:id])

      if @calendar.update(update_calendar_params.except(:start_date))
        redirect_to my_calendar_users_lodging_calendars_path(start_date: update_calendar_params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    def destroy
      @calendar = current_account.user.calendars.find(params[:id])

      if @calendar.destroy
        redirect_to my_calendar_users_lodging_calendars_path(start_date: params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    private

    def create_calendar_params
      params.require(:calendar).permit(:date, :lodging_id, :status, :start_date)
    end

    def update_calendar_params
      params.require(:calendar).permit(:status, :start_date)
    end
  end
end

app/controllers/users/lodging_calendars_controller.rb
# frozen_string_literal: true

module Users
  class LodgingCalendarsController < ApplicationController
    before_action :authenticate_user!

    def index
      @lodging = current_user.lodgings.find(params[:lodging_id])
      @calendars = @lodging.lodging_calendars
    end

    def show
      @lodging = current_user.lodgings.find(params[:lodging_id])
      @user_calendars = current_user.lodging_calendars
    end

    def create
      @calendar = current_user.lodging_calendars.new(create_lodging_params)

      flash[:errors] = @calendar.errors.full_messages unless @calendar.save

      redirect_to users_lodging_lodging_calendars_path(id: params[:originating_id])
    end

    def update
      @calendar = current_user.lodging_calendars.find(params[:id])

      if params[:status] != @calendar.status
        flash[:alert] = 'Values are the same. Update not processed.'
      end

      flash[:errors] = @calendar.errors.full_messages unless @calendar.update(status: params[:status])

      redirect_to users_lodging_lodging_calendars_path
    end

    def destroy
      @calendar = current_user.lodging_calendars.find(params[:id])
      @calendar.destroy

      redirect_to users_lodging_lodging_calendar_path(id: params[:originating_id])
    end

    private

    def create_lodging_params
      params.permit(:lodging_id, :user_id, :start_date, :end_date, :status)
    end

    def update_calendar_params
      params.permit(:status)
    end
  end
end

app/controllers/users/lodgings_controller.rb
# frozen_string_literal: true

module Users
  class LodgingsController < ApplicationController
    before_action :authenticate_account!

    def index
      @lodgings = current_account.user.lodgings
    end

    def show
      @lodging = current_account.user.lodgings.find(params[:id])
    end

    def edit
      @lodging = current_account.user.lodgings.find(params[:id])
    end

    def new
      @lodging = Lodging.new
    end

    def update
      @lodging = current_account.user.lodgings.find(params[:id])

      if @lodging.update(update_lodging_params)
        redirect_to users_lodging_path(@lodging)
      else
        flash.now[:errors] = @lodging.errors.full_messages
        render :edit
      end
    end

    def create
      @lodging = current_account.user.lodgings.new(create_lodging_params)

      if @lodging.save && create_lodging_roommate
        redirect_to users_lodging_path(@lodging)
      else
        flash.now[:errors] = @lodging.errors.full_messages
        render :new
      end
    end

    def destroy
      @lodging = current_account.user.lodgings.find(params[:id])
      @lodging.update(status: :archived)
      redirect_to users_lodgings_path
    end

    private

    def create_lodging_params
      params.require(:lodging).permit(:title, :description, :max_guests, :street, :address2, :city, :state, :zip_code, :country, :status)
    end

    def update_lodging_params
      params.require(:lodging).permit(:title, :description, :max_guests, :status)
    end

    def create_lodging_roommate
      Roommate.create(user_id: current_account.user.id, lodging_id: @lodging.id)
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @lodging = current_user.lodgings.find(params[:lodging_id])
    @photos = @lodging.photos
  end

  def create
    @lodging = current_user.lodgings.find(params[:lodging_id])
    @photo = @lodging.photos.new(photo_params)

    flash[:errors] = @photo.errors.full_messages unless @photo.save
    
    redirect_to users_lodging_photos_path(@lodging)
  end

  def destroy
    
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :photo)
  end
end

app/controllers/users/roommates_controller.rb
# frozen_string_literal: true

module Users
  # brakeman-disable-all
  class RoommatesController < ApplicationController
    before_action :authenticate_account!

    def create
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      roommate = @lodging.roommates.new(roommate_params)
      if roommate.save
        flash[:success]
      else
        flash.now[:errors] = roommate.errors.full_messages
      end
    end

    private

    # brakeman-disable-next-line MassAssignment
    def roommate_params
      params.require(:roommate).permit(:lodging_id, :role, :user_id)
    end
  end
end

app/controllers/users/rooms_controller.rb
# frozen_string_literal: true

module Users
  class RoomsController < ApplicationController
    before_action :authenticate_account!

    def index
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @rooms = @lodging.rooms.all
    end

    def create
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @room = @lodging.rooms.new(room_params)

      flash[:errors] = @room.errors.full_messages unless @room.save

      redirect_to users_lodging_rooms_path(@lodging)
    end

    def destroy
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @room = @lodging.rooms.find(params[:id])
      @room.destroy
      redirect_to users_lodging_rooms_path(@lodging)
    end

    private

    def room_params
      params.require(:room).permit(:room_type, :name, beds_attributes: %i[size style])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_account!

  def index
    @users = User.where.not(id: current_account.user.id)
  end

  def show
    @user = current_account.user
    @resorts = current_account.resort_data_for_multiple_days
  end

  def edit
    @user = current_account.user
  end

  def update
    if current_account.user.update(user_params)
      # redirect_back_or_to user_path
      redirect_to user_path
    else
      flash.now[:errors] = current_account.user.errors.full_messages
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :avatar_url, :first_name, :last_name, :preferred_name, :about, :ride_type, :level, :phone_number, :address1, :address2, :country, :city,
                                 :state, :zip_code, :birthday, :allergies, :venmo_url, :instagram_url, :facebook_url)
  end
end

app/helpers/users/rooms_helper.rb
# frozen_string_literal: true

module Users
  module RoomsHelper
  end
end

app/views/users/lodgings/edit.html.erb
    <h2 class="mt-6 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Edit <%= @lodging.title %></h2>

<%= render partial: 'shared/errors' %>

<div class="space-y-12">
  <%= form_with model: @lodging, url: users_lodging_path do |f| %>
    <div>
      <%= f.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="mt-2">
        <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600">
          <%= f.text_field :title, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>

    <div class="col-span-full mt-3">
      <%= f.label :description, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="mt-2">
        <%= f.text_area :description, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
      </div>
      <p class="mt-3 text-sm leading-6 text-gray-600">Write a few sentences about your lodging.</p>
    </div>

    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
      <div class="mt-3">
        <%= f.label :max_guests, "Max Occupancy", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= f.number_field :max_guests, min: 1, max: 100, step: 1, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600"%>
        </div>
      </div>

      <div class="mt-3">
        <%= f.label :status, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= f.select :status, Lodging.statuses, {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= f.submit class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  <% end %>

app/views/users/lodgings/index.html.erb
<div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
  <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
    <div class="ml-4 mt-2">
      <h3 class="text-base font-semibold leading-6 text-gray-900">Lodgings</h3>
    </div>
    <div class="ml-4 mt-2 flex-shrink-0">
      <%= button_to 'Create New Lodging', new_users_lodging_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
</div>

<% if @lodgings.empty? %>
  <div class="text-center">
    <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
    </svg>
    <h3 class="mt-2 text-sm font-semibold text-gray-900">No Lodgings</h3>
    <p class="mt-1 text-sm text-gray-500">Get started by creating a new lodging.</p>
    <div class="mt-6">
      <button id="newLodgingButton" type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
        </svg>
        New Lodging
      </button>
    </div>
  </div>
<% else %>
  <ul role="list" class="divide-y divide-gray-100">
    <% @lodgings.each do |lodging| %>
      <li class="relative flex justify-between gap-x-6 py-5">
        <div class="flex min-w-0 gap-x-4">
          <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          <div class="min-w-0 flex-auto">
            <p class="text-sm font-semibold leading-6 text-gray-900">
              <a href="<%= users_lodging_path(lodging) %>">
                <span class="absolute inset-x-0 -top-px bottom-0"></span>
                <%= lodging.title %>
              </a>
            </p>
            <p class="mt-1 flex text-xs leading-5 text-gray-500">
              <a href="#" class="relative truncate hover:underline"><%= "#{lodging.street} #{lodging.address2} #{lodging.city} #{lodging.state}" %></a>
            </p>
          </div>
        </div>
        <div class="flex shrink-0 items-center gap-x-4">
          <div class="hidden sm:flex sm:flex-col sm:items-end">
            <p class="text-sm leading-6 text-gray-900"><%= lodging.status %></p>
            <p class="mt-1 text-xs leading-5 text-gray-500">Created at: <%= lodging.created_at %></time></p>
          </div>
        </div>
      </li>
      <%= button_to 'Edit', edit_users_lodging_path(lodging), method: :get %>
      <%= button_to 'Delete', users_lodging_path(lodging), method: :delete %>
    <% end %>  
  </ul>
<% end %>

<script>
  document.getElementById("newLodgingButton").addEventListener("click", function() {
    window.location.href = "<%= new_users_lodging_path %>";
  });
</script>

app/views/users/lodgings/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/errors' %>
<%= render 'shared/notices' %>

<main>
  <div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 grid-rows-1 items-start gap-x-8 gap-y-8 lg:mx-0 lg:max-w-none lg:grid-cols-3">
      <!-- Rooms summary -->
      <div class="lg:col-start-3 lg:row-end-1">
        <h2 class="sr-only">Summary</h2>
        <div class="rounded-lg bg-gray-50 shadow-sm ring-1 ring-gray-900/5">
          <dl class="flex flex-wrap">
            <div class="flex-auto pl-6 pt-6">
              <dt class="text-sm font-semibold leading-6 text-gray-900">Rooms</dt>
            </div>
            <div class="flex-none self-end px-6 pt-4">
              <dt class="sr-only">Status</dt>
              <dd class="rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-600 ring-1 ring-inset ring-green-600/20">Available</dd>
            </div>
            <% @lodging.rooms.each do |room| %>
              <div class="mt-4 flex w-full flex-none gap-x-4 px-6">
                <dt class="flex-none">
                  <span class="sr-only">Status</span>
                  <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M176 256c44.11 0 80-35.89 80-80s-35.89-80-80-80-80 35.89-80 80 35.89 80 80 80zm352-128H304c-8.84 0-16 7.16-16 16v144H64V80c0-8.84-7.16-16-16-16H16C7.16 64 0 71.16 0 80v352c0 8.84 7.16 16 16 16h32c8.84 0 16-7.16 16-16v-48h512v48c0 8.84 7.16 16 16 16h32c8.84 0 16-7.16 16-16V240c0-61.86-50.14-112-112-112z"/></svg>
                </dt>
                <dd class="text-sm leading-6 text-gray-500"><%= room.name %></dd>
              </div>
            <% end %>
          </dl>
        </div>
      </div>

      <!-- Lodging Details -->
      <div class="-mx-4 px-4 py-8 shadow-lg ring-1 ring-gray-900/5 sm:mx-0 sm:rounded-lg sm:px-8 sm:pb-14 lg:col-span-2 lg:row-span-2 lg:row-end-2 xl:px-16 xl:pb-20 xl:pt-16">
        <h2 class="text-base font-semibold leading-6 text-gray-900">Season</h2>
        <dl class="mt-6 grid grid-cols-1 text-sm leading-6 sm:grid-cols-2">
          <div class="sm:pr-4">
            <dt class="inline text-gray-500">Start Date:</dt>
            <dd class="inline text-gray-700"><time datetime="2023-23-01">November 1, 2023</time></dd>
          </div>
          <div class="mt-2 sm:mt-0 sm:pl-4">
            <dt class="inline text-gray-500">End Date:</dt>
            <dd class="inline text-gray-700"><time datetime="2023-31-01">April 30, 2024</time></dd>
          </div>
        </dl>
        <table class="mt-16 w-full whitespace-nowrap text-left text-sm leading-6">
          <colgroup>
            <col class="w-full">
            <col>
            <col>
            <col>
          </colgroup>
          <thead class="border-b border-gray-200 text-gray-900">
            <tr>
              <th scope="col" class="px-0 py-3 font-semibold">This Week</th>
              <th scope="col" class="hidden py-3 pl-8 pr-0 text-right font-semibold sm:table-cell">Staying</th>
              <th scope="col" class="hidden py-3 pl-8 pr-0 text-right font-semibold sm:table-cell">Away</th>
              <th scope="col" class="py-3 pl-8 pr-0 text-right font-semibold">Guests</th>
            </tr>
          </thead>
          <tbody>
            <% @lodging.calendars.this_week.each do |date, counts| %>
              <tr class="border-b border-gray-100">
                <td class="max-w-0 px-0 py-5 align-top">
                  <div class="truncate font-medium text-gray-900"><%= date.strftime('%A') %> - <%= date.day.ordinalize %></div>
                </td>
                <td class="hidden py-5 pl-8 pr-0 text-right align-top tabular-nums text-gray-700 sm:table-cell">
                  <div class="truncate text-gray-500">
                    <div class="flex -space-x-3 rtl:space-x-reverse justify-end">
                      <% counts[:avatar_urls].each do |avatar| %>
                        <img class="w-8 h-8 border-2 border-white rounded-full dark:border-gray-800" src="<%= avatar %>" alt="">
                      <% end %>
                      <a class="flex items-center justify-center w-8 h-8 text-xs font-medium text-white bg-gray-700 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800" href="#"><%= counts[:staying] %></a>
                    </div>
                  </div>
                </td>
                <td class="hidden py-5 pl-8 pr-0 text-right align-top tabular-nums text-gray-700 sm:table-cell"><%= counts[:away] %></td>
                <td class="py-5 pl-8 pr-0 text-right align-top tabular-nums text-gray-700">0</td>
              </tr>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="lg:col-start-3">
        <!-- Activity feed -->
        <h2 class="text-sm font-semibold leading-6 text-gray-900">Activities</h2>
        <ul role="list" class="mt-6 space-y-6">
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Chelsea Hagon</span> created the invoice.</p>
            <time datetime="2023-01-23T10:32" class="flex-none py-0.5 text-xs leading-5 text-gray-500">7d ago</time>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Chelsea Hagon</span> edited the invoice.</p>
            <time datetime="2023-01-23T11:03" class="flex-none py-0.5 text-xs leading-5 text-gray-500">6d ago</time>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Chelsea Hagon</span> sent the invoice.</p>
            <time datetime="2023-01-23T11:24" class="flex-none py-0.5 text-xs leading-5 text-gray-500">6d ago</time>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <img src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="relative mt-3 h-6 w-6 flex-none rounded-full bg-gray-50">
            <div class="flex-auto rounded-md p-3 ring-1 ring-inset ring-gray-200">
              <div class="flex justify-between gap-x-4">
                <div class="py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Chelsea Hagon</span> commented</div>
                <time datetime="2023-01-23T15:56" class="flex-none py-0.5 text-xs leading-5 text-gray-500">3d ago</time>
              </div>
              <p class="text-sm leading-6 text-gray-500">Called client, they reassured me the invoice would be paid by the 25th.</p>
            </div>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Alex Curren</span> viewed the invoice.</p>
            <time datetime="2023-01-24T09:12" class="flex-none py-0.5 text-xs leading-5 text-gray-500">2d ago</time>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center h-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <svg class="h-6 w-6 text-indigo-600" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm13.36-1.814a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clip-rule="evenodd" />
              </svg>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Alex Curren</span> paid the invoice.</p>
            <time datetime="2023-01-24T09:20" class="flex-none py-0.5 text-xs leading-5 text-gray-500">1d ago</time>
          </li>
        </ul>
      </div>
    </div>
  </div>
</main>

<%= form_with url: users_lodging_roommates_path(lodging_id: params[:id]) do |form| %>
  <%= form.fields_for :roommate do |roommate_form| %>
    <%= roommate_form.collection_select :role, Roommate.roles.to_a, :first, :last %>
    <%= roommate_form.collection_select :user_id, User.all, :id, ->(user) { "#{user.first_name} #{user.last_name}" } %>
  <% end %>
  <%= form.submit 'Add Roommate' %>
<% end %>