config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  resource :user, only: %i[show edit update]
  resources :users, only: :index

  namespace :users do
    resources :lodgings do
      resources :roommates, only: :create
      resources :rooms, only: %i[index create destroy]
      resource :calendars, only: %i[show create destroy update] do
        get 'my_calendar', on: :member
      end
    end
  end

  get '/edit-profile', to: 'accounts#edit', as: 'edit_profile'
  patch '/edit-profile', to: 'accounts#update'
  delete '/account_season_pass/:season_pass_id', to: 'accounts#season_pass_destroy', as: 'remove_season_pass'

  devise_for :accounts, controllers: {
    omniauth_callbacks: 'accounts/omniauth_callbacks',
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations'
  }
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :lodging
  has_many :beds
  accepts_nested_attributes_for :beds

  validates :name, presence: true

  enum room_type: {
    bedroom: 'bedroom',
    livingroom: 'livingroom'
  }, _default: 'bedroom'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :roommates
  has_many :lodgings, through: :roommates
  belongs_to :account
  has_many :calendars, dependent: :destroy

  validates :first_name, :last_name, :ride_type, presence: true, length: { minimum: 2 }

  enum :ride_type, {
    ski: 'ski',
    snowboard: 'snowboard',
    both: 'ski and snowboard'
  }, prefix: true, _default: 'ski'

  enum :level, {
    beginner: 'beginner',
    intermediate: 'intermediate',
    advanced: 'advanced'
  }, _default: 'beginner'

  def initials
    "#{first_name&.first || ''}#{last_name&.first || ''}".upcase
  end
end

app/controllers/users/calendars_controller.rb
# frozen_string_literal: true

module Users
  class CalendarsController < ApplicationController
    before_action :authenticate_account!

    def show
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @lodging_calendars = @lodging.calendars.grouped_by_date_with_avatars(params[:start_date]&.to_date || Date.today)
    end

    def my_calendar
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @calendars = current_account.user.calendars.where(lodging_id: params[:lodging_id])
    end

    def create
      @calendar = current_account.user.calendars.new(create_calendar_params.except(:start_date))

      if @calendar.save
        redirect_to my_calendar_users_lodging_calendars_path(start_date: create_calendar_params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    def update
      @calendar = current_account.user.calendars.find(params[:id])

      if @calendar.update(update_calendar_params.except(:start_date))
        redirect_to my_calendar_users_lodging_calendars_path(start_date: update_calendar_params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    def destroy
      @calendar = current_account.user.calendars.find(params[:id])

      if @calendar.destroy
        redirect_to my_calendar_users_lodging_calendars_path(start_date: params[:start_date])
      else
        flash.now[:errors] = @calendar.errors.full_messages
      end
    end

    private

    def create_calendar_params
      params.require(:calendar).permit(:date, :lodging_id, :status, :start_date)
    end

    def update_calendar_params
      params.require(:calendar).permit(:status, :start_date)
    end
  end
end

app/controllers/users/lodging_calendars_controller.rb
# frozen_string_literal: true

module Users
  class LodgingCalendarsController < ApplicationController
    before_action :authenticate_user!

    def index
      @lodging = current_user.lodgings.find(params[:lodging_id])
      @calendars = @lodging.lodging_calendars
    end

    def show
      @lodging = current_user.lodgings.find(params[:lodging_id])
      @user_calendars = current_user.lodging_calendars
    end

    def create
      @calendar = current_user.lodging_calendars.new(create_lodging_params)

      flash[:errors] = @calendar.errors.full_messages unless @calendar.save

      redirect_to users_lodging_lodging_calendars_path(id: params[:originating_id])
    end

    def update
      @calendar = current_user.lodging_calendars.find(params[:id])

      if params[:status] != @calendar.status
        flash[:alert] = 'Values are the same. Update not processed.'
      end

      flash[:errors] = @calendar.errors.full_messages unless @calendar.update(status: params[:status])

      redirect_to users_lodging_lodging_calendars_path
    end

    def destroy
      @calendar = current_user.lodging_calendars.find(params[:id])
      @calendar.destroy

      redirect_to users_lodging_lodging_calendar_path(id: params[:originating_id])
    end

    private

    def create_lodging_params
      params.permit(:lodging_id, :user_id, :start_date, :end_date, :status)
    end

    def update_calendar_params
      params.permit(:status)
    end
  end
end

app/controllers/users/lodgings_controller.rb
# frozen_string_literal: true

module Users
  class LodgingsController < ApplicationController
    before_action :authenticate_account!

    def index
      @lodgings = current_account.user.lodgings
    end

    def show
      @lodging = current_account.user.lodgings.find(params[:id])
    end

    def edit
      @lodging = current_account.user.lodgings.find(params[:id])
    end

    def new
      @lodging = Lodging.new
    end

    def update
      @lodging = current_account.user.lodgings.find(params[:id])

      if @lodging.update(update_lodging_params)
        redirect_to users_lodging_path(@lodging)
      else
        flash.now[:errors] = @lodging.errors.full_messages
        render :edit
      end
    end

    def create
      @lodging = current_account.user.lodgings.new(create_lodging_params)

      if @lodging.save && create_lodging_roommate
        redirect_to users_lodging_path(@lodging)
      else
        flash.now[:errors] = @lodging.errors.full_messages
        render :new
      end
    end

    def destroy
      @lodging = current_account.user.lodgings.find(params[:id])
      @lodging.update(status: :archived)
      redirect_to users_lodgings_path
    end

    private

    def create_lodging_params
      params.require(:lodging).permit(:title, :description, :max_guests, :street, :address2, :city, :state, :zip_code, :country, :status)
    end

    def update_lodging_params
      params.require(:lodging).permit(:title, :description, :max_guests, :status)
    end

    def create_lodging_roommate
      Roommate.create(user_id: current_account.user.id, lodging_id: @lodging.id)
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @lodging = current_user.lodgings.find(params[:lodging_id])
    @photos = @lodging.photos
  end

  def create
    @lodging = current_user.lodgings.find(params[:lodging_id])
    @photo = @lodging.photos.new(photo_params)

    flash[:errors] = @photo.errors.full_messages unless @photo.save
    
    redirect_to users_lodging_photos_path(@lodging)
  end

  def destroy
    
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :photo)
  end
end

app/controllers/users/roommates_controller.rb
# frozen_string_literal: true

module Users
  # brakeman-disable-all
  class RoommatesController < ApplicationController
    before_action :authenticate_account!

    def create
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      roommate = @lodging.roommates.new(roommate_params)
      if roommate.save
        flash[:success]
      else
        flash.now[:errors] = roommate.errors.full_messages
      end
    end

    private

    # brakeman-disable-next-line MassAssignment
    def roommate_params
      params.require(:roommate).permit(:lodging_id, :role, :user_id)
    end
  end
end

app/controllers/users/rooms_controller.rb
# frozen_string_literal: true

module Users
  class RoomsController < ApplicationController
    before_action :authenticate_account!

    def index
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @rooms = @lodging.rooms.all
    end

    def create
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @room = @lodging.rooms.new(room_params)

      flash[:errors] = @room.errors.full_messages unless @room.save

      redirect_to users_lodging_rooms_path(@lodging)
    end

    def destroy
      @lodging = current_account.user.lodgings.find(params[:lodging_id])
      @room = @lodging.rooms.find(params[:id])
      @room.destroy
      redirect_to users_lodging_rooms_path(@lodging)
    end

    private

    def room_params
      params.require(:room).permit(:room_type, :name, beds_attributes: %i[size style])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_account!

  def index
    @users = User.where.not(id: current_account.user.id)
  end

  def show
    @user = current_account.user
    @resorts = current_account.resort_data_for_multiple_days
  end

  def edit
    @user = current_account.user
  end

  def update
    if current_account.user.update(user_params)
      # redirect_back_or_to user_path
      redirect_to user_path
    else
      flash.now[:errors] = current_account.user.errors.full_messages
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :avatar_url, :first_name, :last_name, :preferred_name, :about, :ride_type, :level, :phone_number, :address1, :address2, :country, :city,
                                 :state, :zip_code, :birthday, :allergies, :venmo_url, :instagram_url, :facebook_url)
  end
end

app/helpers/users/rooms_helper.rb
# frozen_string_literal: true

module Users
  module RoomsHelper
  end
end

app/views/users/rooms/_form.html.erb
<div data-controller="room">

  <template data-room-target="bedFields">
    <label class="block text-sm font-medium leading-6 text-gray-900">Bed Size</label>
      <select name="room[beds_attributes][][size]" class="mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">

        <% Bed.sizes.each do |size, _|%>
          <option><%= size %></option>
        <% end%>

      </select>

    <label class="block text-sm font-medium leading-6 text-gray-900">Bed Style</label>
      <select name="room[beds_attributes][][style]" class="mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">

        <% Bed.styles.each do |style, _|%>
          <option><%= style %></option>
        <% end%>

      </select>
  </template>
  
  <form action="<%= users_lodging_rooms_path(lodging) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div class="sm:col-span-2 sm:col-start-1">
      <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
      <div class="mt-2">
        <input type="text" name="room[name]" id="name" value="" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
      </div>
    </div>

    <label for="room_type" class="block text-sm font-medium leading-6 text-gray-900">Room Type</label>
    <select id="room_type" name="room[room_type]" class="mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">

        <% Room.room_types.each do |rt, _|%>
        <option><%= rt %></option>
        <% end%>

      </select>

      <fieldset data-room-target="beds">
      <legend>Beds</legend>
      </fieldset>

      <a href="#" data-action="room#addBed">Add Bed</a>

    <input type="submit" value="Add Room">
  </form>
</div>

app/views/users/rooms/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users::Rooms#create</h1>
  <p>Find me in app/views/users/rooms/create.html.erb</p>
</div>

app/views/users/rooms/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Users::Rooms#destroy</h1>
  <p>Find me in app/views/users/rooms/destroy.html.erb</p>
</div>

app/views/users/rooms/index.html.erb
<%= render 'shared/header' %>
<%= render partial: 'shared/errors' %>
<%= render partial: 'shared/notices' %>

<div class="bg-grey shadow overflow-hidden sm:rounded-md">
  <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @rooms.each do |room| %>
    <li class="col-span-1 flex flex-col divide-y divide-gray-200 rounded-lg bg-white text-center shadow">
      <div class="flex flex-1 flex-col p-8">
        <%# <img class="mx-auto h-32 w-32 flex-shrink-0 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt=""> %>
        <h3 class="mt-6 text-sm font-medium text-gray-900"><%= "#{room.name.capitalize} #{room.room_type.capitalize}" %><% "#{room.beds.count}" %></h3>
        <% room.beds.each do |bed| %>
          <div class="mt-5">
              <span class="inline-flex items-center rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Available</span>
            <div class="rounded-md bg-gray-50 px-6 py-5 sm:flex sm:items-start sm:justify-between">
              <div class="sm:flex sm:items-start">

                <div class="mt-3 sm:ml-4 sm:mt-0">
                  <div class="text-sm font-medium text-gray-900"><%= "#{bed.size.capitalize} #{bed.style.capitalize}" %></div>
                  <%# <div class="mt-1 text-sm text-gray-600 sm:flex sm:items-center">
                    <div>Expires 12/20</div>
                    <span class="hidden sm:mx-2 sm:inline" aria-hidden="true">&middot;</span>
                    <div class="mt-1 sm:mt-0">Last updated on 22 Aug 2017</div>
                  </div> %>
                </div>
              </div>
              <%# <div class="mt-4 sm:ml-6 sm:mt-0 sm:flex-shrink-0">
                <button type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Edit</button>
              </div> %>
            </div>
          </div>

        <% end %>
      </div>
      <div>
        <div class="-mt-px flex divide-x divide-gray-200">
          <div class="flex w-0 flex-1">
            <a href="mailto:janecooper@example.com" class="relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900">
              <%# <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"> %>
                <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
                <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
              </svg>
              Edit
            </a>
          </div>
          <div class="-ml-px flex w-0 flex-1">
            <%= link_to "Delete", users_lodging_room_path(@lodging, room), method: :delete, class: "relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border border-transparent py-4 text-sm font-semibold text-gray-900" %>
          </div>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<%= render partial: 'form', locals: { lodging: @lodging } %>